### ISSUE TITLE
react-native-fast-image Fails

### ISSUE THREAD

**Issue by pavankumarkl** [DylanVann/react-native-fast-image#448]
Followed below steps: 
npm i react-native-fast-image --save
npm link
and when I run app I get below error 
" (0 , _react.forwardRef) is not a function "

**Comment by romreed** [comment]
same issue "react-native": "0.59.6" android

**Comment by romreed** [comment]
@pavankumarkl upgrade your react to v16.6.0

**Comment by AlcuinGuest** [comment]
Same here, but with react.memo instead of react.forwardRef. @romreed 's solution worked for me.

**Comment by sturmenta** [comment]
<img width="393" alt="Captura de Pantalla 2019-04-25 a la(s) 16 17 16" src="https://user-images.githubusercontent.com/30802967/56764026-22430780-677a-11e9-9e53-b206f64ee4f9.png">

after update react to 16.6.0, its work!

thanks to @romreed comment

**Comment by DylanVann** [comment]
RNFI only targets the latest version of React Native, which has an associated React version.

You will need to upgrade to a version of React later than 16.8.3.

**Comment by pavankumarkl** [comment]
thanks for your reply

@dylanvann

**Comment by nitinkumar24** [comment]
@AlcuinGuest I am still getting this error.
    "react": "^16.6.0",
    "react-native-fast-image": "^5.2.0",
    "redux": "^4.0.0",
    "react-redux": "^5.0.7",
    "react-native": "0.57.2",
