### ISSUE TITLE
Image/webp Support

### ISSUE THREAD

**Issue by armandoarmando** [DylanVann/react-native-fast-image#397]
Hi Everyone! I saw many entries about webp format support with posible solutions, but doesn't works for me #385 #92 #386
In the meanwhile, I wanna use the Image native component for Webp format. I tried the param fallback but doesn't work. Any solution? Many thanks!

**Comment by bbturtle** [comment]
Follow #326 . Hope it helps you

**Comment by DylanVann** [comment]
I think it's fixed, thanks @bbturtle!

https://github.com/DylanVann/react-native-fast-image/releases/tag/v5.1.3

**Comment by armandoarmando** [comment]
Hi! I'm trying to build with version 5.1.3 and I receive this error: 

```
Image/FLAnimatedImage/FLAnimatedImageView+WebCache.m:18:9: fatal error: 'UIImage+MemoryCacheCost.h' file not found
#import "UIImage+MemoryCacheCost.h"
        ^~~~~~~~~~~~~~~~~~~~~~~~~~~
1 error generated.


** BUILD FAILED **
```

TIA!

**Comment by DylanVann** [comment]
I suspect you just need to clean in Xcode. If that doesn't work try [these troubleshooting steps](https://github.com/DylanVann/react-native-fast-image/blob/master/docs/troubleshooting.md).

**Comment by DylanVann** [comment]
The fallback prop was also broken 🤦‍♂️, so it makes sense it didn't work for you either.

See: https://github.com/DylanVann/react-native-fast-image/releases/tag/v5.1.4

**Comment by armandoarmando** [comment]
> The fallback prop was also broken 🤦‍♂️, so it makes sense it didn't work for you either.
> 
> See: https://github.com/DylanVann/react-native-fast-image/releases/tag/v5.1.4

Works for me! Thanks!!!

**Comment by bbturtle** [comment]
> Hi! I'm trying to build with version 5.1.3 and I receive this error:
> 
> ```
> Image/FLAnimatedImage/FLAnimatedImageView+WebCache.m:18:9: fatal error: 'UIImage+MemoryCacheCost.h' file not found
> #import "UIImage+MemoryCacheCost.h"
>         ^~~~~~~~~~~~~~~~~~~~~~~~~~~
> 1 error generated.
> 
> 
> ** BUILD FAILED **
> ```
> TIA!

You can use version 5.1.2, completely running smoothly except for webp support on iOS.
