### ISSUE TITLE
package com.facebook.react.views.imagehelper does not exist [FIX THIS QUICK]

### ISSUE THREAD

**Issue by preto89** [DylanVann/react-native-fast-image#369]
REACT NATIVE FAST IMAGE DOESNT WORK AT ALL NOT EVEN GOD CAN MAKE IT WORK OMG FIX THIS!

```
Note: [2] Wrote GeneratedAppGlideModule with: [com.bumptech.glide.integration.okhttp3.OkHttpLibraryGlideModule, com.dylanvann.fastimage.FastImageOkHttpProgressGlideModule]
node_modules/react-native-fast-image/android/src/main/java/com/dylanvann/fastimage/FastImageViewConverter.java:23: error:package com.facebook.react.views.imagehelper does not exist
import com.facebook.react.views.imagehelper.ImageSource;
                                           ^
node_modules/react-native-fast-image/android/src/main/java/com/dylanvann/fastimage/FastImageSource.java:10: error: package com.facebook.react.views.imagehelper does not exist
import com.facebook.react.views.imagehelper.ImageSource;
                                           ^
node_modules/react-native-fast-image/android/src/main/java/com/dylanvann/fastimage/FastImageSource.java:14: error: cannotfind symbol
public class FastImageSource extends ImageSource {
                                     ^
  symbol: class ImageSource
node_modules/react-native-fast-image/android/src/main/java/com/dylanvann/fastimage/FastImageViewModule.java:12: error: package com.facebook.react.views.imagehelper does not exist
import com.facebook.react.views.imagehelper.ImageSource;
                                           ^
4 errors


FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':react-native-fast-image:compileDebugJavaWithJavac'.
> Compilation failed; see the compiler error output for details.
```

Ive done all of this manually: https://github.com/DylanVann/react-native-fast-image/blob/master/docs/installation-manual.md

Already cleared cache from everywhere, deleted node modules millions of times, this doenst work at all, it was a simple installation nothing too complex. PLEASE FIX THIS OMG

I cant run this on Android.

already downgraded version, nothing seems to work, the plugin is broken please fix it...
dont tell people useless solutions like in the other issue from the same subject please OMG!

**Comment by bbturtle** [comment]
please try add in Proguard
If you use Proguard you will need to add these lines to android/app/proguard-rules.pro:

-keep public class com.dylanvann.fastimage.* {*;}
-keep public class com.dylanvann.fastimage.** {*;}

**Comment by bbturtle** [comment]
Does your project show package fast-images in module?
![image](https://user-images.githubusercontent.com/42196041/49915088-7b468900-fec6-11e8-8aa5-d46c90a210d7.png)

**Comment by lucidtheory** [comment]
i also am running into this issue. Added these prograurd rules and also the fast-image module shows up in my project as above ^

**Comment by bbturtle** [comment]
Can you clear cache and rebuild, try it.

**Comment by lucidtheory** [comment]
hey that worked! I'm curious why that worked.

**Comment by jmxxii** [comment]
Tried all of this. No luck!
Environment: {
"react-native": "^0.58.4",
"react-native-fast-image": "^5.1.2"
"gradleVersion": "4.4"
}

**Comment by ithustle** [comment]
Still no working

**Comment by bbturtle** [comment]
@jmxxii  @ithustle 
Follow link:
https://github.com/DylanVann/react-native-fast-image/blob/master/docs/installation-manual.md

Which operating system (Android or iOS) are you running?
You can try clearing the cache of npm and running again

**Comment by ithustle** [comment]
@jmxxii , I'm working with both but I'm having this problem on Android. I've tried many times to rebuild on Android Studio and nothing...  

It's working fine until a few minutes throw this issue ... I cleared the cache and no luck

**Comment by bbturtle** [comment]
> @jmxxii , I'm working with both but I'm having this problem on Android. I've tried many times to rebuild on Android Studio and nothing...
> 
> It's worked fine until a few minutes throw this issue ... I cleared the cache and no luck

Can you take pictures of Fast Image modules in your Android project?

**Comment by jmxxii** [comment]
Ok well I managed to fix mine. Turns out to be an SDK issue at least on my end. I was using targetSDKVersion 26 I switched it to 22. I synced and reset cache and it worked without a problem. Although I haven't tried other versions. Hope this helps @ithustle 
Check your android/app/build.gradle for your sdk version.

**Comment by ithustle** [comment]
@jmxxii it helped. Thanks. 
You too @bbturtle ;)

**Comment by xstable** [comment]
For me it happends after upgrading RN from 0.58.7 to 0.58.8.
Removing `node_modules`-Directory and run `yarn install` was the solution.

**Comment by Ilphrin** [comment]
@preto89 Yelling "FIX THIS QUICK" will not make things go faster. Please consider that people here use freely their spare time to help other people, so just be nice please ;)
Anyway, did you tried the solutions from @jmxxii, @xstable or @bbturtle ? If it is working for you please tell us so the maintainer of this package can close this issue =D

**Comment by Pushpak-123** [comment]
Hello all, I am also facing same error. I tried all above solutions but none is working. I am getting error as 

```
Error:(10, 44) error: package com.facebook.react.views.imagehelper does not exist
Error:(14, 38) error: cannot find symbol class ImageSource

```
My RN version is "react-native": "^0.59.8",

**Comment by rochapablo** [comment]
I'm getting the follow error right after config [webview](https://github.com/react-native-community/react-native-webview/issues/580#issuecomment-500853867):

```
> Task :react-native-fast-image:compileDebugJavaWithJavac FAILED
Gradle may disable incremental compilation as the following annotation processors are not incremental: jetified-compiler-4.7.1.jar (com.github.bumptech.glide:compiler:4.7.1).
Consider setting the experimental feature flag android.enableSeparateAnnotationProcessing=true in the gradle.properties file to run annotation processing in a separate task and make compilation incremental.
Note: [2] Wrote GeneratedAppGlideModule with: [com.bumptech.glide.integration.okhttp3.OkHttpLibraryGlideModule, com.dylanvann.fastimage.FastImageOkHttpProgressGlideModule]
node_modules/react-native-fast-image/android/src/main/java/com/dylanvann/fastimage/FastImageOkHttpProgressGlideModule.java:6: error: package android.support.annotation does not exist
import android.support.annotation.NonNull;
                                 ^
node_modules/react-native-fast-image/android/build/generated/source/apt/debug/com/dylanvann/fastimage/GlideOptions.java:6: error: package android.support.annotation does not exist
import android.support.annotation.CheckResult;
                                 ^
node_modules/react-native-fast-image/android/build/generated/source/apt/debug/com/dylanvann/fastimage/GlideOptions.java:7: error: package android.support.annotation does not exist
import android.support.annotation.NonNull;
                                 ^
node_modules/react-native-fast-image/android/build/generated/source/apt/debug/com/dylanvann/fastimage/GlideRequest.java:8: error: package android.support.annotation does not exist
import android.support.annotation.CheckResult;
                                 ^
node_modules/react-native-fast-image/android/build/generated/source/apt/debug/com/dylanvann/fastimage/GlideRequest.java:9: error: package android.support.annotation does not exist
import android.support.annotation.NonNull;
                                 ^
node_modules/react-native-fast-image/android/build/generated/source/apt/debug/com/dylanvann/fastimage/GlideRequests.java:7: error: package android.support.annotation does not exist
import android.support.annotation.CheckResult;
                                 ^
node_modules/react-native-fast-image/android/build/generated/source/apt/debug/com/dylanvann/fastimage/GlideRequests.java:8: error: package android.support.annotation does not exist
import android.support.annotation.NonNull;
                                 ^
node_modules/react-native-fast-image/android/build/generated/source/apt/debug/com/bumptech/glide/GeneratedRequestManagerFactory.java:4: error: package android.support.annotation does not exist
import android.support.annotation.NonNull;
                                 ^
node_modules/react-native-fast-image/android/build/generated/source/apt/debug/com/bumptech/glide/GeneratedAppGlideModuleImpl.java:4: error: package android.support.annotation does not exist
import android.support.annotation.NonNull;
                                 ^
node_modules/react-native-fast-image/android/src/main/java/com/dylanvann/fastimage/FastImageOkHttpProgressGlideModule.java:41: error: cannot find symbol
            @NonNull Context context,
             ^
  symbol:   class NonNull
  location: class FastImageOkHttpProgressGlideModule
node_modules/react-native-fast-image/android/src/main/java/com/dylanvann/fastimage/FastImageOkHttpProgressGlideModule.java:42: error: cannot find symbol
            @NonNull Glide glide,
             ^
  symbol:   class NonNull
  location: class FastImageOkHttpProgressGlideModule
node_modules/react-native-fast-image/android/src/main/java/com/dylanvann/fastimage/FastImageOkHttpProgressGlideModule.java:43: error: cannot find symbol
            @NonNull Registry registry
             ^
  symbol:   class NonNull
  location: class FastImageOkHttpProgressGlideModule
node_modules/react-native-fast-image/android/src/main/java/com/dylanvann/fastimage/FastImageRequestListener.java:34: error: package android.support.annotation does not exist
    public boolean onLoadFailed(@android.support.annotation.Nullable GlideException e, Object model, Target<Drawable> target, boolean isFirstResource) {
                                                           ^
node_modules/react-native-fast-image/android/build/generated/source/apt/debug/com/dylanvann/fastimage/GlideOptions.java:48: error: cannot find symbol
  @CheckResult
   ^
  symbol:   class CheckResult
  location: class GlideOptions
node_modules/react-native-fast-image/android/build/generated/source/apt/debug/com/dylanvann/fastimage/GlideOptions.java:49: error: cannot find symbol
  @NonNull
   ^
  symbol:   class NonNull
  location: class GlideOptions
node_modules/react-native-fast-image/android/build/generated/source/apt/debug/com/dylanvann/fastimage/GlideOptions.java:57: error: cannot find symbol
  @CheckResult
   ^
  symbol:   class CheckResult
  location: class GlideOptions
node_modules/react-native-fast-image/android/build/generated/source/apt/debug/com/dylanvann/fastimage/GlideOptions.java:58: error: cannot find symbol
  @NonNull
   ^
  symbol:   class NonNull
  location: class GlideOptions
node_modules/react-native-fast-image/android/build/generated/source/apt/debug/com/dylanvann/fastimage/GlideOptions.java:66: error: cannot find symbol
  @CheckResult
   ^
  symbol:   class CheckResult
  location: class GlideOptions
node_modules/react-native-fast-image/android/build/generated/source/apt/debug/com/dylanvann/fastimage/GlideOptions.java:67: error: cannot find symbol
  @NonNull
   ^
  symbol:   class NonNull
  location: class GlideOptions
node_modules/react-native-fast-image/android/build/generated/source/apt/debug/com/dylanvann/fastimage/GlideOptions.java:75: error: cannot find symbol
  @CheckResult
   ^
  symbol:   class CheckResult
  location: class GlideOptions
node_modules/react-native-fast-image/android/build/generated/source/apt/debug/com/dylanvann/fastimage/GlideOptions.java:76: error: cannot find symbol
  @NonNull
   ^
  symbol:   class NonNull
  location: class GlideOptions
node_modules/react-native-fast-image/android/build/generated/source/apt/debug/com/dylanvann/fastimage/GlideOptions.java:84: error: cannot find symbol
  @CheckResult
   ^
  symbol:   class CheckResult
  location: class GlideOptions
node_modules/react-native-fast-image/android/build/generated/source/apt/debug/com/dylanvann/fastimage/GlideOptions.java:85: error: cannot find symbol
  @NonNull
   ^
  symbol:   class NonNull
  location: class GlideOptions
node_modules/react-native-fast-image/android/build/generated/source/apt/debug/com/dylanvann/fastimage/GlideOptions.java:93: error: cannot find symbol
  @CheckResult
   ^
  symbol:   class CheckResult
  location: class GlideOptions
node_modules/react-native-fast-image/android/build/generated/source/apt/debug/com/dylanvann/fastimage/GlideOptions.java:94: error: cannot find symbol
  @NonNull
   ^
  symbol:   class NonNull
  location: class GlideOptions
node_modules/react-native-fast-image/android/build/generated/source/apt/debug/com/dylanvann/fastimage/GlideOptions.java:102: error: cannot find symbol
  @CheckResult
   ^
  symbol:   class CheckResult
  location: class GlideOptions
node_modules/react-native-fast-image/android/build/generated/source/apt/debug/com/dylanvann/fastimage/GlideOptions.java:103: error: cannot find symbol
  @NonNull
   ^
  symbol:   class NonNull
  location: class GlideOptions
node_modules/react-native-fast-image/android/build/generated/source/apt/debug/com/dylanvann/fastimage/GlideOptions.java:111: error: cannot find symbol
  @CheckResult
   ^
  symbol:   class CheckResult
  location: class GlideOptions
node_modules/react-native-fast-image/android/build/generated/source/apt/debug/com/dylanvann/fastimage/GlideOptions.java:112: error: cannot find symbol
  @NonNull
   ^
  symbol:   class NonNull
  location: class GlideOptions
node_modules/react-native-fast-image/android/build/generated/source/apt/debug/com/dylanvann/fastimage/GlideOptions.java:120: error: cannot find symbol
  @CheckResult
   ^
  symbol:   class CheckResult
  location: class GlideOptions
node_modules/react-native-fast-image/android/build/generated/source/apt/debug/com/dylanvann/fastimage/GlideOptions.java:121: error: cannot find symbol
  @NonNull
   ^
  symbol:   class NonNull
  location: class GlideOptions
node_modules/react-native-fast-image/android/build/generated/source/apt/debug/com/dylanvann/fastimage/GlideOptions.java:130: error: cannot find symbol
  @CheckResult
   ^
  symbol:   class CheckResult
  location: class GlideOptions
node_modules/react-native-fast-image/android/build/generated/source/apt/debug/com/dylanvann/fastimage/GlideOptions.java:131: error: cannot find symbol
  @NonNull
   ^
  symbol:   class NonNull
  location: class GlideOptions
node_modules/react-native-fast-image/android/build/generated/source/apt/debug/com/dylanvann/fastimage/GlideOptions.java:139: error: cannot find symbol
  @CheckResult
   ^
  symbol:   class CheckResult
  location: class GlideOptions
node_modules/react-native-fast-image/android/build/generated/source/apt/debug/com/dylanvann/fastimage/GlideOptions.java:140: error: cannot find symbol
  @NonNull
   ^
  symbol:   class NonNull
  location: class GlideOptions
node_modules/react-native-fast-image/android/build/generated/source/apt/debug/com/dylanvann/fastimage/GlideOptions.java:148: error: cannot find symbol
  @CheckResult
   ^
  symbol:   class CheckResult
  location: class GlideOptions
node_modules/react-native-fast-image/android/build/generated/source/apt/debug/com/dylanvann/fastimage/GlideOptions.java:149: error: cannot find symbol
  @NonNull
   ^
  symbol:   class NonNull
  location: class GlideOptions
node_modules/react-native-fast-image/android/build/generated/source/apt/debug/com/dylanvann/fastimage/GlideOptions.java:161: error: cannot find symbol
  @CheckResult
   ^
  symbol:   class CheckResult
  location: class GlideOptions
node_modules/react-native-fast-image/android/build/generated/source/apt/debug/com/dylanvann/fastimage/GlideOptions.java:162: error: cannot find symbol
  @NonNull
   ^
  symbol:   class NonNull
  location: class GlideOptions
node_modules/react-native-fast-image/android/build/generated/source/apt/debug/com/dylanvann/fastimage/GlideOptions.java:174: error: cannot find symbol
  @CheckResult
   ^
  symbol:   class CheckResult
  location: class GlideOptions
node_modules/react-native-fast-image/android/build/generated/source/apt/debug/com/dylanvann/fastimage/GlideOptions.java:175: error: cannot find symbol
  @NonNull
   ^
  symbol:   class NonNull
  location: class GlideOptions
node_modules/react-native-fast-image/android/build/generated/source/apt/debug/com/dylanvann/fastimage/GlideOptions.java:187: error: cannot find symbol
  @CheckResult
   ^
  symbol:   class CheckResult
  location: class GlideOptions
node_modules/react-native-fast-image/android/build/generated/source/apt/debug/com/dylanvann/fastimage/GlideOptions.java:188: error: cannot find symbol
  @NonNull
   ^
  symbol:   class NonNull
  location: class GlideOptions
node_modules/react-native-fast-image/android/build/generated/source/apt/debug/com/dylanvann/fastimage/GlideOptions.java:200: error: cannot find symbol
  @CheckResult
   ^
  symbol:   class CheckResult
  location: class GlideOptions
node_modules/react-native-fast-image/android/build/generated/source/apt/debug/com/dylanvann/fastimage/GlideOptions.java:201: error: cannot find symbol
  @NonNull
   ^
  symbol:   class NonNull
  location: class GlideOptions
node_modules/react-native-fast-image/android/build/generated/source/apt/debug/com/dylanvann/fastimage/GlideOptions.java:209: error: cannot find symbol
  @CheckResult
   ^
  symbol:   class CheckResult
  location: class GlideOptions
node_modules/react-native-fast-image/android/build/generated/source/apt/debug/com/dylanvann/fastimage/GlideOptions.java:210: error: cannot find symbol
  @NonNull
   ^
  symbol:   class NonNull
  location: class GlideOptions
node_modules/react-native-fast-image/android/build/generated/source/apt/debug/com/dylanvann/fastimage/GlideOptions.java:222: error: cannot find symbol
  @CheckResult
   ^
  symbol:   class CheckResult
  location: class GlideOptions
node_modules/react-native-fast-image/android/build/generated/source/apt/debug/com/dylanvann/fastimage/GlideOptions.java:223: error: cannot find symbol
  @NonNull
   ^
  symbol:   class NonNull
  location: class GlideOptions
node_modules/react-native-fast-image/android/build/generated/source/apt/debug/com/dylanvann/fastimage/GlideOptions.java:232: error: cannot find symbol
  @CheckResult
   ^
  symbol:   class CheckResult
  location: class GlideOptions
node_modules/react-native-fast-image/android/build/generated/source/apt/debug/com/dylanvann/fastimage/GlideOptions.java:233: error: cannot find symbol
  @NonNull
   ^
  symbol:   class NonNull
  location: class GlideOptions
node_modules/react-native-fast-image/android/build/generated/source/apt/debug/com/dylanvann/fastimage/GlideOptions.java:241: error: cannot find symbol
  @CheckResult
   ^
  symbol:   class CheckResult
  location: class GlideOptions
node_modules/react-native-fast-image/android/build/generated/source/apt/debug/com/dylanvann/fastimage/GlideOptions.java:242: error: cannot find symbol
  @NonNull
   ^
  symbol:   class NonNull
  location: class GlideOptions
node_modules/react-native-fast-image/android/build/generated/source/apt/debug/com/dylanvann/fastimage/GlideOptions.java:250: error: cannot find symbol
  @CheckResult
   ^
  symbol:   class CheckResult
  location: class GlideOptions
node_modules/react-native-fast-image/android/build/generated/source/apt/debug/com/dylanvann/fastimage/GlideOptions.java:251: error: cannot find symbol
  @NonNull
   ^
  symbol:   class NonNull
  location: class GlideOptions
node_modules/react-native-fast-image/android/build/generated/source/apt/debug/com/dylanvann/fastimage/GlideOptions.java:259: error: cannot find symbol
  @CheckResult
   ^
  symbol:   class CheckResult
  location: class GlideOptions
node_modules/react-native-fast-image/android/build/generated/source/apt/debug/com/dylanvann/fastimage/GlideOptions.java:260: error: cannot find symbol
  @NonNull
   ^
  symbol:   class NonNull
  location: class GlideOptions
node_modules/react-native-fast-image/android/build/generated/source/apt/debug/com/dylanvann/fastimage/GlideOptions.java:268: error: cannot find symbol
  @CheckResult
   ^
  symbol:   class CheckResult
  location: class GlideOptions
node_modules/react-native-fast-image/android/build/generated/source/apt/debug/com/dylanvann/fastimage/GlideOptions.java:269: error: cannot find symbol
  @NonNull
   ^
  symbol:   class NonNull
  location: class GlideOptions
node_modules/react-native-fast-image/android/build/generated/source/apt/debug/com/dylanvann/fastimage/GlideOptions.java:277: error: cannot find symbol
  @CheckResult
   ^
  symbol:   class CheckResult
  location: class GlideOptions
node_modules/react-native-fast-image/android/build/generated/source/apt/debug/com/dylanvann/fastimage/GlideOptions.java:278: error: cannot find symbol
  @NonNull
   ^
  symbol:   class NonNull
  location: class GlideOptions
node_modules/react-native-fast-image/android/build/generated/source/apt/debug/com/dylanvann/fastimage/GlideOptions.java:286: error: cannot find symbol
  @CheckResult
   ^
  symbol:   class CheckResult
  location: class GlideOptions
node_modules/react-native-fast-image/android/build/generated/source/apt/debug/com/dylanvann/fastimage/GlideOptions.java:287: error: cannot find symbol
  @NonNull
   ^
  symbol:   class NonNull
  location: class GlideOptions
node_modules/react-native-fast-image/android/build/generated/source/apt/debug/com/dylanvann/fastimage/GlideOptions.java:295: error: cannot find symbol
  @CheckResult
   ^
  symbol:   class CheckResult
  location: class GlideOptions
node_modules/react-native-fast-image/android/build/generated/source/apt/debug/com/dylanvann/fastimage/GlideOptions.java:296: error: cannot find symbol
  @NonNull
   ^
  symbol:   class NonNull
  location: class GlideOptions
node_modules/react-native-fast-image/android/build/generated/source/apt/debug/com/dylanvann/fastimage/GlideRequest.java:56: error: cannot find symbol
  GlideRequest(@NonNull Class<TranscodeType> transcodeClass, @NonNull RequestBuilder<?> other) {
                ^
  symbol:   class NonNull
  location: class GlideRequest<TranscodeType>
  where TranscodeType is a type-variable:
    TranscodeType extends Object declared in class GlideRequest
node_modules/react-native-fast-image/android/build/generated/source/apt/debug/com/dylanvann/fastimage/GlideRequest.java:56: error: cannot find symbol
  GlideRequest(@NonNull Class<TranscodeType> transcodeClass, @NonNull RequestBuilder<?> other) {
                                                              ^
  symbol:   class NonNull
  location: class GlideRequest<TranscodeType>
  where TranscodeType is a type-variable:
    TranscodeType extends Object declared in class GlideRequest
node_modules/react-native-fast-image/android/build/generated/source/apt/debug/com/dylanvann/fastimage/GlideRequest.java:60: error: cannot find symbol
  GlideRequest(@NonNull Glide glide, @NonNull RequestManager requestManager,
                ^
  symbol:   class NonNull
  location: class GlideRequest<TranscodeType>
  where TranscodeType is a type-variable:
    TranscodeType extends Object declared in class GlideRequest
node_modules/react-native-fast-image/android/build/generated/source/apt/debug/com/dylanvann/fastimage/GlideRequest.java:60: error: cannot find symbol
  GlideRequest(@NonNull Glide glide, @NonNull RequestManager requestManager,
                                      ^
  symbol:   class NonNull
  location: class GlideRequest<TranscodeType>
  where TranscodeType is a type-variable:
    TranscodeType extends Object declared in class GlideRequest
node_modules/react-native-fast-image/android/build/generated/source/apt/debug/com/dylanvann/fastimage/GlideRequest.java:61: error: cannot find symbol
      @NonNull Class<TranscodeType> transcodeClass, @NonNull Context context) {
       ^
  symbol:   class NonNull
  location: class GlideRequest<TranscodeType>
  where TranscodeType is a type-variable:
    TranscodeType extends Object declared in class GlideRequest
node_modules/react-native-fast-image/android/build/generated/source/apt/debug/com/dylanvann/fastimage/GlideRequest.java:61: error: cannot find symbol
      @NonNull Class<TranscodeType> transcodeClass, @NonNull Context context) {
                                                     ^
  symbol:   class NonNull
  location: class GlideRequest<TranscodeType>
  where TranscodeType is a type-variable:
    TranscodeType extends Object declared in class GlideRequest
node_modules/react-native-fast-image/android/build/generated/source/apt/debug/com/dylanvann/fastimage/GlideRequest.java:66: error: cannot find symbol
  @CheckResult
   ^
  symbol:   class CheckResult
  location: class GlideRequest<TranscodeType>
  where TranscodeType is a type-variable:
    TranscodeType extends Object declared in class GlideRequest
node_modules/react-native-fast-image/android/build/generated/source/apt/debug/com/dylanvann/fastimage/GlideRequest.java:67: error: cannot find symbol
  @NonNull
   ^
  symbol:   class NonNull
  location: class GlideRequest<TranscodeType>
  where TranscodeType is a type-variable:
    TranscodeType extends Object declared in class GlideRequest
node_modules/react-native-fast-image/android/build/generated/source/apt/debug/com/dylanvann/fastimage/GlideRequests.java:36: error: cannot find symbol
  public GlideRequests(@NonNull Glide glide, @NonNull Lifecycle lifecycle,
                        ^
  symbol:   class NonNull
  location: class GlideRequests
node_modules/react-native-fast-image/android/build/generated/source/apt/debug/com/dylanvann/fastimage/GlideRequests.java:36: error: cannot find symbol
  public GlideRequests(@NonNull Glide glide, @NonNull Lifecycle lifecycle,
                                              ^
  symbol:   class NonNull
  location: class GlideRequests
node_modules/react-native-fast-image/android/build/generated/source/apt/debug/com/dylanvann/fastimage/GlideRequests.java:37: error: cannot find symbol
      @NonNull RequestManagerTreeNode treeNode, @NonNull Context context) {
       ^
  symbol:   class NonNull
  location: class GlideRequests
node_modules/react-native-fast-image/android/build/generated/source/apt/debug/com/dylanvann/fastimage/GlideRequests.java:37: error: cannot find symbol
      @NonNull RequestManagerTreeNode treeNode, @NonNull Context context) {
                                                 ^
  symbol:   class NonNull
  location: class GlideRequests
node_modules/react-native-fast-image/android/build/generated/source/apt/debug/com/dylanvann/fastimage/GlideRequests.java:44: error: cannot find symbol
  public <ResourceType> GlideRequest<ResourceType> as(@NonNull Class<ResourceType> resourceClass) {
                                                       ^
  symbol:   class NonNull
  location: class GlideRequests
node_modules/react-native-fast-image/android/build/generated/source/apt/debug/com/dylanvann/fastimage/GlideRequests.java:42: error: cannot find symbol
  @CheckResult
   ^
  symbol:   class CheckResult
  location: class GlideRequests
node_modules/react-native-fast-image/android/build/generated/source/apt/debug/com/dylanvann/fastimage/GlideRequests.java:43: error: cannot find symbol
  @NonNull
   ^
  symbol:   class NonNull
  location: class GlideRequests
node_modules/react-native-fast-image/android/build/generated/source/apt/debug/com/dylanvann/fastimage/GlideRequests.java:49: error: cannot find symbol
  @NonNull
   ^
  symbol:   class NonNull
  location: class GlideRequests
node_modules/react-native-fast-image/android/build/generated/source/apt/debug/com/dylanvann/fastimage/GlideRequests.java:55: error: cannot find symbol
  @NonNull
   ^
  symbol:   class NonNull
  location: class GlideRequests
node_modules/react-native-fast-image/android/build/generated/source/apt/debug/com/dylanvann/fastimage/GlideRequests.java:166: error: cannot find symbol
  protected void setRequestOptions(@NonNull RequestOptions toSet) {
                                    ^
  symbol:   class NonNull
  location: class GlideRequests
node_modules/react-native-fast-image/android/build/generated/source/apt/debug/com/bumptech/glide/GeneratedRequestManagerFactory.java:17: error: cannot find symbol
  public RequestManager build(@NonNull Glide glide, @NonNull Lifecycle lifecycle,
                               ^
  symbol:   class NonNull
  location: class GeneratedRequestManagerFactory
node_modules/react-native-fast-image/android/build/generated/source/apt/debug/com/bumptech/glide/GeneratedRequestManagerFactory.java:17: error: cannot find symbol
  public RequestManager build(@NonNull Glide glide, @NonNull Lifecycle lifecycle,
                                                     ^
  symbol:   class NonNull
  location: class GeneratedRequestManagerFactory
node_modules/react-native-fast-image/android/build/generated/source/apt/debug/com/bumptech/glide/GeneratedRequestManagerFactory.java:18: error: cannot find symbol
      @NonNull RequestManagerTreeNode treeNode, @NonNull Context context) {
       ^
  symbol:   class NonNull
  location: class GeneratedRequestManagerFactory
node_modules/react-native-fast-image/android/build/generated/source/apt/debug/com/bumptech/glide/GeneratedRequestManagerFactory.java:18: error: cannot find symbol
      @NonNull RequestManagerTreeNode treeNode, @NonNull Context context) {
                                                 ^
  symbol:   class NonNull
  location: class GeneratedRequestManagerFactory
node_modules/react-native-fast-image/android/build/generated/source/apt/debug/com/bumptech/glide/GeneratedRequestManagerFactory.java:16: error: cannot find symbol
  @NonNull
   ^
  symbol:   class NonNull
  location: class GeneratedRequestManagerFactory
node_modules/react-native-fast-image/android/build/generated/source/apt/debug/com/bumptech/glide/GeneratedAppGlideModuleImpl.java:29: error: cannot find symbol
  public void applyOptions(@NonNull Context context, @NonNull GlideBuilder builder) {
                            ^
  symbol:   class NonNull
  location: class GeneratedAppGlideModuleImpl
node_modules/react-native-fast-image/android/build/generated/source/apt/debug/com/bumptech/glide/GeneratedAppGlideModuleImpl.java:29: error: cannot find symbol
  public void applyOptions(@NonNull Context context, @NonNull GlideBuilder builder) {
                                                      ^
  symbol:   class NonNull
  location: class GeneratedAppGlideModuleImpl
node_modules/react-native-fast-image/android/build/generated/source/apt/debug/com/bumptech/glide/GeneratedAppGlideModuleImpl.java:34: error: cannot find symbol
  public void registerComponents(@NonNull Context context, @NonNull Glide glide,
                                  ^
  symbol:   class NonNull
  location: class GeneratedAppGlideModuleImpl
node_modules/react-native-fast-image/android/build/generated/source/apt/debug/com/bumptech/glide/GeneratedAppGlideModuleImpl.java:34: error: cannot find symbol
  public void registerComponents(@NonNull Context context, @NonNull Glide glide,
                                                            ^
  symbol:   class NonNull
  location: class GeneratedAppGlideModuleImpl
node_modules/react-native-fast-image/android/build/generated/source/apt/debug/com/bumptech/glide/GeneratedAppGlideModuleImpl.java:35: error: cannot find symbol
      @NonNull Registry registry) {
       ^
  symbol:   class NonNull
  location: class GeneratedAppGlideModuleImpl
node_modules/react-native-fast-image/android/build/generated/source/apt/debug/com/bumptech/glide/GeneratedAppGlideModuleImpl.java:47: error: cannot find symbol
  @NonNull
   ^
  symbol:   class NonNull
  location: class GeneratedAppGlideModuleImpl
node_modules/react-native-fast-image/android/build/generated/source/apt/debug/com/bumptech/glide/GeneratedAppGlideModuleImpl.java:53: error: cannot find symbol
  @NonNull
   ^
  symbol:   class NonNull
  location: class GeneratedAppGlideModuleImpl
95 errors

FAILURE: Build failed with an exception.
```

```
"react": "16.8.3",
"react-native": "0.59.9",
"react-native-fast-image": "^6.0.3",
```

**Comment by tusharmutreja** [comment]
@rochapablo I am getting the same problem, did you find any solution?

**Comment by chakravorty** [comment]
@tusharmutreja  @rochapablo  also facing that issue

**Comment by rochapablo** [comment]
@tusharmutreja, @chakravorty, kind of, [this is what I had to do](https://github.com/DylanVann/react-native-fast-image/issues/480#issuecomment-500878746)

**Comment by origamih** [comment]
My fix is to download `https://github.com/DylanVann/react-native-fast-image`, then put the `android/` folder to `node_modules/react-native-fast-image/` overwrite everything (basically you use the latest `android` not `ios`)

**Comment by RediaUa** [comment]
It helps me 
https://github.com/DylanVann/react-native-fast-image/blob/master/docs/app-glide-module.md
